# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-MaxMind-HTTPBase
version:      1.43
version_from: lib/Business/MaxMind/HTTPBase.pm
installdirs:  site
requires:
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
